apiVersion: v1
kind: Secret
metadata:
  name: dms-secrets
  namespace: dms
type: Opaque
stringData:
  JWT_SECRET: "dms-super-secret-jwt-key-2026"
  PG_PASSWORD: "dms123"
  S3_ACCESS_KEY: "minioadmin"
  S3_SECRET_KEY: "minioadmin"
  GROQ_API_KEY: "your-groq-api-key-here"